# Generated by Django 4.0.5 on 2022-06-18 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sourceproduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inwarddocument',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sourceproduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderconfirmation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sourceproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sourceproduct'),
        ),
    ]
