# Generated by Django 4.0.5 on 2022-06-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_invoice_product_inwarddocument_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnc',
            name='version',
            field=models.SmallIntegerField(),
        ),
    ]
