# Generated by Django 4.0.5 on 2022-06-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.PositiveIntegerField()),
                ('about', models.TextField()),
                ('customer_type', models.CharField(choices=[('customer', 'Customer'), ('ns', 'NS'), ('nc', 'NC')], max_length=50)),
                ('product', models.CharField(choices=[('Steel', 'steel'), ('Spring', 'spring')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.PositiveIntegerField()),
                ('about', models.TextField()),
                ('customer_type', models.CharField(choices=[('customer', 'Customer'), ('ns', 'NS'), ('nc', 'NC')], max_length=50)),
                ('product', models.CharField(choices=[('Steel', 'steel'), ('Spring', 'spring')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.PositiveIntegerField()),
                ('about', models.TextField()),
                ('customer_type', models.CharField(choices=[('customer', 'Customer'), ('ns', 'NS'), ('nc', 'NC')], max_length=50)),
                ('product', models.CharField(choices=[('Steel', 'steel'), ('Spring', 'spring')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
