# Generated by Django 4.0.5 on 2022-06-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='nclient',
            name='contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='nsource',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
