# Generated by Django 4.0.5 on 2022-06-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_contact_alter_nclient_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='nclient',
            name='product',
        ),
        migrations.RemoveField(
            model_name='nsource',
            name='product',
        ),
    ]
